// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxxqddoytczvrzuaykwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4eHFkZG95dGN6dnJ6dWF5a3doIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2NDY3MTMsImV4cCI6MjA1NTIyMjcxM30.I4Pk3Jad90OUzqGf1QkmzvVi2UeKkSuSwmxw0KJEsV4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);